import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import { ApiProvider } from "@/context/ApiContext";
import DemoNotification from "@/components/Notification";

export const metadata = {
  title: "Gaprio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ApiProvider>
          <Navbar />
          {children}
          <Footer />
          <DemoNotification />
        </ApiProvider>
      </body>
    </html>
  );
}
